version: "3"
services:
  nod_dev_env:
    build: .
    container_name: node-docker
    ports:
      - 8080:3000
    volumes:
      - ./:/home/app
    networks:
      - swarm-test-network

networks:
  swarm-test-network:
    external: true
